"""Really add torrent table

Revision ID: e81bf5c23c5f
Revises: f8eddecb5db2
Create Date: 2025-11-26 21:02:19.882777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81bf5c23c5f'
down_revision: Union[str, Sequence[str], None] = 'f8eddecb5db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrent',
    sa.Column('info_hash', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_torrent_id'), 'torrent', ['id'], unique=False)
    op.create_index(op.f('ix_torrent_info_hash'), 'torrent', ['info_hash'], unique=True)
    op.create_index(op.f('ix_torrent_title'), 'torrent', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_torrent_title'), table_name='torrent')
    op.drop_index(op.f('ix_torrent_info_hash'), table_name='torrent')
    op.drop_index(op.f('ix_torrent_id'), table_name='torrent')
    op.drop_table('torrent')
    # ### end Alembic commands ###
